<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <!-- 测试内文件操作无需响应取消，抑制 xUnit1051 -->
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YetAnotherGameLauncher.Channels.Kuro\YetAnotherGameLauncher.Channels.Kuro.csproj" />
    <ProjectReference Include="..\YetAnotherGameLauncher.TestSupport\YetAnotherGameLauncher.TestSupport.csproj" />
  </ItemGroup>

</Project>
